# Generated by Django 3.1.3 on 2021-03-03 03:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10)),
                ('serverip', models.GenericIPAddressField(protocol='IPv4')),
                ('serverpubkey', models.CharField(max_length=200)),
                ('serverprivkey', models.CharField(max_length=200)),
                ('endpoint', models.CharField(max_length=200)),
                ('port', models.IntegerField()),
                ('subred', models.GenericIPAddressField(protocol='IPv4')),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pubkey', models.CharField(max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Conexion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(protocol='IPv4')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vpnapp.perfil')),
                ('interfaz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vpnapp.aula')),
            ],
            options={
                'unique_together': {('alumno', 'interfaz')},
            },
        ),
        migrations.AddField(
            model_name='aula',
            name='clientes',
            field=models.ManyToManyField(through='vpnapp.Conexion', to='vpnapp.Perfil'),
        ),
    ]
