# Generated by Django 3.1.3 on 2020-12-06 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpnapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aula',
            name='subred',
            field=models.GenericIPAddressField(blank=True, null=True, protocol='IPv4'),
        ),
    ]
