# Generated by Django 3.1.3 on 2020-12-06 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpnapp', '0002_aula_subred'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aula',
            name='subred',
            field=models.GenericIPAddressField(protocol='IPv4'),
        ),
    ]
